---
version: '3.5'

services:
  # Base image using ubuntu
  veolia-idf-ubuntu:
    build:
      context: .
      args: [--rm]
      dockerfile: ./Dockerfile
    # user: docker
    working_dir: /workdir
    environment:
      DISPLAY: host.docker.internal:0.0
      NO_AT_BRIDGE: 1
    volumes:
      - .:/workdir

  veolia-run-ubuntu:
    extends: veolia-idf-ubuntu
    command: ./veolia-idf-domoticz.py --run

  # Base image using alpine
  veolia-idf-alpine:
    build:
      context: .
      args: [--rm]
      dockerfile: ./DockerfileAlpine
      # dockerfile: ./DockerfileDebian
    # user: docker
    working_dir: /workdir
    environment:
      DISPLAY: host.docker.internal:0.0
      NO_AT_BRIDGE: 1
    volumes:
      - .:/workdir

  # Run script in normal mode
  #
  # Run this using `docker compose run --rm veolia-run` on the CLI
  veolia-run:
    extends: veolia-idf-alpine
    command: ./veolia-idf-domoticz.py --run

  # Run script in debug mode and keep the CSV
  #
  # Run this using `docker compose run --rm veolia-run` on the CLI
  veolia-debug:
    extends: veolia-idf-alpine
    command: ./veolia-idf-domoticz.py --run --debug --keep_csv

  veolia-debug-local:
    extends: veolia-idf-alpine
    command: ./veolia-idf-domoticz.py --run --debug --keep_csv --local-config

  veolia-debug-veolia:
    extends: veolia-idf-alpine
    command: python3 -m trace --ignore-dir=/usr/lib -t ./veolia-idf-domoticz.py --run --debug --keep_csv --veolia

  # Map Windows Debian XServer to Docker and use its XServer
  #  Note: works first time, Windows'XServer seems to fail after that.
  veolia-wind:
    extends: veolia-debug-local
    environment:
      DISPLAY: :0
    volumes:
      - \\wsl.localhost\Debian\mnt\wslg\.X11-unix:/tmp/.X11-unix
      - \\wsl.localhost\Debian\mnt\wslg\PulseServer:/tmp/PulseServer
      - \\wsl.localhost\Debian\mnt\wslg\PulseAudioRDPSink:/tmp/PulseAudioRDPSink
      - \\wsl.localhost\Debian\mnt\wslg\PulseAudioRDPSource:/tmp/PulseAudioRDPSource
